apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: n03sk8jlh-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/n03sk8jlh-dotnet-basic-gitops